[Settings]
  ID = "466a973b-da09-4199-b203-f3ff430583dc"

[Build]
  Publish = ""
  Functions = ""

[[redirects]]
from = "/*/amp-rewrite"
to = "https://www.google.com/:splat"
status = 200
force = false

[[redirects]]
from = "/*/amp-redirect"
to = "https://www.google.com/:splat"
status = 301
force = false

[[redirects]]
from = "/google"
to = "https://www.google.com"
status = 200
force = false

[[redirects]]
from = "/google-redirect/*"
to = "https://www.google.com/:splat"
status = 301
force = false